### ISSUE TITLE
As a teacher should I be able to change the pupil's details?

### ISSUE THREAD

**Issue by psiotwo** [koty10/online-edu#9]
I was surprised to find out that - logged as a pupil - I am able to change the details of a pupil (e.g. date of birth!, name ! ... )

**Comment by koty10** [comment]
According to the name of an issue, I suppose that you meant "logged as a teacher". That seems fine to me. As I mention in chapter 4.9 in my thesis text - I prefer a variant that an administrator creates classrooms and teachers, and a teacher creates students in a given classroom. The work is then better divided between an admin and teachers.
